algoritmo "SomaParametrosReferencia"

var
x, y: Inteiro
Procedimento Soma (var a, b: Inteiro)
inicio
      a <- a + 1
      b<- b + 2
      Escreval("Valor de A = ", a)
      Escreval("Valor de B = ", b)
      Escreval("Soma A + B = ", a+b)
      FimProcedimento
inicio

      x <- 4

      y<- 8

    Soma (x, y)
     Escreval("Valor de X = ", x)
     Escreval("Valor de Y = ", y)

Fimalgoritmo