algoritmo "semnome"
var
   mai, cont, idade: inteiro
     Procedimento maior ()
     inicio
           Escreval("A maior idade digitada até agora é ", mai)
     FimProcedimento
inicio
      mai <- 0
      cont <- 1
      Enquanto (cont <= 5) faca
      Escreval("Digite a sua idade:")
      Leia(idade)
      Se (idade > mai) entao
          mai <-  idade
      FimSE
      limpatela
      maior

      cont <- cont  +1
      Fimenquanto

fimalgoritmo